services:
  server:
    build: .
    container_name: bia
    ports:
      - 80:8080
    depends_on:
      - database
    environment:
      DB_USER: postgres
      DB_PWD: postgres
      DB_HOST: database
      DB_PORT: 5432